### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Mentos302** [Mentos302/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by typeCabel** [comment]
Привіт, я відомий український репер, актор, спортсмен, мотиватор, танцюрист та шоумен. Народився у с. Хлівище. Популярність здобув завдяки своїм трекам, зокрема «Маямі», «Коронавірус», «Спорт сила» та блогу в соціальній мережі Instagram.

**Comment by typeCabel** [comment]
Hi, I am a famous Ukrainian rapper, actor, athlete, motivator, dancer and showman. I was born in the village Khlivische. I gained popularity thanks to my tracks, including "Miami", "Coronavirus", "Sport Syla!" and a blog on the social network Instagram.
