### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Mentos302** [Mentos302/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by typeCabel** [comment]
EXPERIENCE

2019 Found a producer Gerald Estrada and began active songwriting process

2017 Active Instagram interaction

2015 Casting for Ukraine has talent

2011 First song about my beloved

2010 Buy first laptop and started began to write songs

2007 Began to do horizontal bars and workout 

2005 Went to study as a pastry chef in college

2005 Graduated middle school.

1996 Went to first grade!

1990 Born in Khlivische, Chernivetska Oblast, Ukraine.
