### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Mentos302** [Mentos302/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by typeCabel** [comment]
LANGUAGES
UKRAINIAN RUSSIAN POLISH
SKILLS
rapper, actor, athlete, motivator, dancer and showman
CHARACTER
STRAIGHTFORWARD DEBATER CONFIDENT CONTENTIOUS COMMANDER EMPATHETIC CURIOUS PROCRASTINATOR EASY-GOING SPONTANEOUS DRAMATIC MOTIVATOR
LIKES😃
SPORT ORANGE JUICE RAP MUSIC MC SONYA 
DISLIKES😞
ALCOHOL DRUGS TATOOS SHOWING HIGH-HATTERS DRUG-DEALERS
